#### tmux 5
Device=2
DefRec_on_trgt=False
DefRec_weight=0.02

Norm_on_trgt=True
Density_on_trgt=False

Density_normal_viainput=True
Density_normal_defpart=False
Normal_ondef=False
Density_ondef=True

Normal_pred_weight=0.01

Withstr='complete'

Density_weight=0.01
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset faust  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef  --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset adobe  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset scape  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset faust  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput  --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset scape  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset adobe  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

Density_weight=0.02
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset faust  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef  --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset adobe  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset scape  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset faust  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput  --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset scape  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset adobe  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

Density_weight=0.05
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset faust  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef  --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset adobe  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset scape  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset faust  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput  --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset scape  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset adobe  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

Density_weight=0.1
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset faust  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef  --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset adobe  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset scape  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset faust  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput  --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset scape  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset adobe  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

Density_weight=0.2
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset faust  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef  --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset adobe  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset scape  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset faust  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput  --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset scape  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset adobe  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight



# # #### tmux 6
# Device=2

# Normal_pred_weight=0.02
# Density_weight=0.01
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset faust  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef  --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset adobe  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset scape  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset faust  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput  --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset scape  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset adobe  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

# Density_weight=0.02
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset faust  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef  --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset adobe  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset scape  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset faust  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput  --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset scape  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset adobe  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

# Density_weight=0.05
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset faust  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef  --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset adobe  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset scape  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset faust  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput  --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset scape  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset adobe  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

# Density_weight=0.1
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset faust  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef  --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset adobe  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset scape  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset faust  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput  --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset scape  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset adobe  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

# Density_weight=0.2
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset faust  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef  --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset scape --trgt_dataset adobe  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset scape  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset adobe --trgt_dataset faust  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput  --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset scape  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset mit  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight
# CUDA_VISIBLE_DEVICES=$Device python trainer.py  --out_path '../../DAexperiments/seg/density'$Density_weight'_norm_'$Normal_pred_weight'_'$Withstr  --dataroot ../../PointSegDAdataset/  --src_dataset faust --trgt_dataset adobe  --DefRec_on_trgt=$DefRec_on_trgt  --DefRec_weight=$DefRec_weight --Density_normal_viainput=$Density_normal_viainput --Normal_ondef=$Normal_ondef --Density_ondef=$Density_ondef --Density_weight=$Density_weight --Density_normal_defpart=$Density_normal_defpart  --Density_on_trgt=$Density_on_trgt --Norm_on_trgt=$Norm_on_trgt --normal_pred_weight=$Normal_pred_weight

